# Generated by Django 4.2.7 on 2023-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=80)),
                ('birthday', models.DateField()),
                ('introphrase', models.TextField()),
                ('introtext', models.TextField()),
                ('logo', models.CharField(max_length=80)),
                ('photo', models.CharField(max_length=80)),
                ('userid', models.BigIntegerField()),
            ],
        ),
    ]
