# Generated by Django 4.2.7 on 2023-11-13 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geninfo',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='introphrase',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction phrase'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='introtext',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction paragraph'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='logo',
            field=models.ImageField(default='users/logo_default.jpg', upload_to='users/', verbose_name='User logo'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='photo',
            field=models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='user photo'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='profession',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geninfo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
