# Generated by Django 4.2.7 on 2023-11-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfapp', '0002_alter_geninfo_options_alter_geninfo_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geninfo',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Geninfo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
