# Generated by Django 4.2.7 on 2023-11-13 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfapp', '0004_rename_userid_geninfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geninfo',
            options={'ordering': ['-id'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geninfo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
