# Generated by Django 4.2.7 on 2023-11-14 23:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfapp', '0005_alter_geninfo_options_alter_geninfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk01name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 01')),
                ('sk01x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk02name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 02')),
                ('sk02x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk03name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 03')),
                ('sk03x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk04name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 04')),
                ('sk04x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk05name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 05')),
                ('sk05x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk06name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 06')),
                ('sk06x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk07name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 07')),
                ('sk07x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk08name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 08')),
                ('sk08x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk09name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 09')),
                ('sk09x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sk10name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Skill 10')),
                ('sk10x100', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr01name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Project 01')),
                ('pr01description', models.TextField(blank=True, null=True, verbose_name='Project 01 description')),
                ('pr01pho01', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 01 photo 01')),
                ('pr01pho02', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 01 photo 02')),
                ('pr01pho03', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 01 photo 03')),
                ('pr01pho04', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 01 photo 04')),
                ('pr01pho05', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 01 photo 05')),
                ('pr02name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Project 02')),
                ('pr02description', models.TextField(blank=True, null=True, verbose_name='Project 02 description')),
                ('pr02pho01', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 02 photo 01')),
                ('pr02pho02', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 02 photo 02')),
                ('pr02pho03', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 02 photo 03')),
                ('pr02pho04', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 02 photo 04')),
                ('pr02pho05', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 02 photo 05')),
                ('pr03name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Project 03')),
                ('pr03description', models.TextField(blank=True, null=True, verbose_name='Project 03 description')),
                ('pr03pho01', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 03 photo 01')),
                ('pr03pho02', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 03 photo 02')),
                ('pr03pho03', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 03 photo 03')),
                ('pr03pho04', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 03 photo 04')),
                ('pr03pho05', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 03 photo 05')),
                ('pr04name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Project 04')),
                ('pr04description', models.TextField(blank=True, null=True, verbose_name='Project 04 description')),
                ('pr04pho01', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 04 photo 01')),
                ('pr04pho02', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 04 photo 02')),
                ('pr04pho03', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 04 photo 03')),
                ('pr04pho04', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 04 photo 04')),
                ('pr04pho05', models.ImageField(default='users/user_default.jpg', upload_to='users/', verbose_name='Project 04 photo 05')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
